version: '3'
services:
  streamlit-app:
    build:
      context: .  # Path to your app's directory
    ports:
      - "8501:8501"  # Expose Streamlit on port 8501
    environment:
      AWS_ACCESS_KEY_ID:  
      AWS_SECRET_ACCESS_KEY: test